const archiveItems = [
  {
    id: "west-europe-2025",
    title: "WEST EUROPE",
    duration: "11days",
    date: "2025.12.15 ~ 12.25",
    location: "ROME-FIRENZE-GRINDELWALD-PARIS",
    tags: ["ROME", "FIRENZE", "GRINDELWALD", "PARIS"],
    caption: "Honeymoon: Nayeon’s Guided Tour – The Fight Ending",
    image: "/archive/west-europe.jpg",
  },
  {
    id: "mexico-peru-2025",
    title: "MEXICO-PERU",
    duration: "15days",
    date: "2025.03.21 ~ 04.05",
    location: "CANCUN-CUSCO-MEXICOCITY",
    tags: ["CANCÚN", "CUSCO", "MEXICO CITY"],
    caption: "FINDING TEOTIHUACAN & MACHU PICCHU AFTER A GRUELING JOURNEY",
    image: "/archive/mexico-peru.jpeg",
  },
  {
    id: "france-suisse-2024",
    title: "FRANCE-SUISSE",
    duration: "14days",
    date: "2024.07.24 ~ 08.06",
    location: "CHAMONIX-LAUSANNE-ZERMATT-GRINDELWALD-LUCERNE-BASEL",
    tags: ["Chamonix", "Lausanne", "Zermatt", "Grindelwald", "Lucerne", "Basel"],
    caption: "For trekking the three great peaks: Mont Blanc, the Matterhorn, and the Jungfrau.",
    image: "/archive/france-suisse.jpg",
  },
  {
    id: "german-norway-danmark-2023",
    title: "NORDIC",
    duration: "16days",
    date: "2023.08.23 ~ 09.07",
    location: "FRANKFURT-HEIDELBERG-NUREMBERG-STRASBOURG-BERGEN-STAVANGER-COPENHAGEN",
    tags: ["Frankfurt", "Heidelberg", "Nuremberg", "Strasbourg", "Bergen", "Stavanger", "Copenhagen"],
    caption: "Using my cousin's wedding as an excuse to knock out Norway's three big treks.",
    image: "/archive/german-norway-danmark.jpg",
  },
  {
    id: "italia-2022",
    title: "ITALIA",
    duration: "14days",
    date: "2022.09.22 ~ 10.05",
    location: "MILANO-BOLZANO-CORTINA-FIRENZE-TOSCANA-ROME",
    tags: ["Milano", "Bolzano", "Cortina d'Ampezzo", "Firenze", "Toscana", "Rome"],
    caption: "My first trip since COVID — trekking the Dolomites in the Alps.",
    image: "/archive/italia.jpg",
  },
];

window.archiveItems = archiveItems;
