const musicItems = [
  {
    id: "music-1",
    title: "ARCHIVE MIX.",
    duration: "8tracks",
    date: "2025.01.12",
    location: "SEOUL",
    tags: ["SEOUL", "NIGHT"],
    caption: "A late mix kept only as memory and sound.",
    image: "/archive/archive-1.svg",
  },
  {
    id: "music-2",
    title: "ARCHIVE MIX.",
    duration: "12tracks",
    date: "2024.06.08",
    location: "TOKYO",
    tags: ["TOKYO", "LIVE"],
    caption: "Notes from a room that no longer exists.",
    image: "/archive/archive-2.svg",
  },
  {
    id: "music-3",
    title: "ARCHIVE MIX.",
    duration: "9tracks",
    date: "2023.11.02",
    location: "BERLIN",
    tags: ["BERLIN", "CLUB"],
    caption: "Bass still ringing after the lights came up.",
    image: "/archive/archive-3.svg",
  },
  {
    id: "music-4",
    title: "ARCHIVE MIX.",
    duration: "10tracks",
    date: "2023.04.18",
    location: "LONDON",
    tags: ["LONDON", "RADIO"],
    caption: "Tracks I played when I could not sleep.",
    image: "/archive/archive-4.svg",
  },
  {
    id: "music-5",
    title: "ARCHIVE MIX.",
    duration: "7tracks",
    date: "2022.09.30",
    location: "NEW YORK",
    tags: ["NYC", "VINYL"],
    caption: "The first record I carried across an ocean.",
    image: "/archive/archive-1.svg",
  },
];

window.musicItems = musicItems;
