const musicItems = [
  {
    id: "steve-lacy-2026",
    title: "STEVE LACY",
    duration: "1show",
    date: "2026.08.19",
    location: "SEOUL",
    tags: ["SEOUL", "OLYMPIC HALL"],
    caption: "스티브 레이시 첫 단독 내한공연",
    image: "/archive/steve-lacy.jpg",
    detail: {
      titleSvg: "assets/images/steve-lacy-title.png",
      rows: [
        { label: "공연명", value: "스티브 레이시 첫 단독 내한공연" },
        { label: "공연 일시", value: "2026년 8월 19일 (수) 오후 8시" },
        { label: "공연 장소", value: "올림픽공원 올림픽홀" },
      ],
      body: "스티브 레이시는 밴드 The Internet의 기타리스트 겸 보컬로 이름을 알린 뒤, 솔로 아티스트로 독자적인 그루브를 쌓아 왔다. 이미 몇 차례 내한해 한국 관객과 호흡한 그는 2026년, 정규 앨범 [Oh Yeah?]를 들고 처음으로 단독 내한공연을 연다. 올림픽홀 스탠딩 앞에서 그의 특유의 즉흥 연주와 나른한 보컬을 가장 가까이에서 만날 수 있는 밤이다.",
      tags: ["SEOUL", "OLYMPIC HALL", "26.08.19"],
      images: [
        "/archive/steve-lacy.jpg",
        "/archive/steve-lacy-2.jpg",
        "/archive/steve-lacy-3.jpg",
      ],
    },
  },
  {
    id: "music-2",
    title: "ARCHIVE MIX.",
    duration: "12tracks",
    date: "2024.06.08",
    location: "TOKYO",
    tags: ["TOKYO", "LIVE"],
    caption: "Notes from a room that no longer exists.",
    image: "/archive/archive-2.svg",
  },
  {
    id: "music-3",
    title: "ARCHIVE MIX.",
    duration: "9tracks",
    date: "2023.11.02",
    location: "BERLIN",
    tags: ["BERLIN", "CLUB"],
    caption: "Bass still ringing after the lights came up.",
    image: "/archive/archive-3.svg",
  },
  {
    id: "music-4",
    title: "ARCHIVE MIX.",
    duration: "10tracks",
    date: "2023.04.18",
    location: "LONDON",
    tags: ["LONDON", "RADIO"],
    caption: "Tracks I played when I could not sleep.",
    image: "/archive/archive-4.svg",
  },
  {
    id: "music-5",
    title: "ARCHIVE MIX.",
    duration: "7tracks",
    date: "2022.09.30",
    location: "NEW YORK",
    tags: ["NYC", "VINYL"],
    caption: "The first record I carried across an ocean.",
    image: "/archive/archive-1.svg",
  },
];

window.musicItems = musicItems;
